name: Docker Image CI

on:
  push:
    branches: [ "tests" ]
  pull_request:
    branches: [ "tests" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd test && ./test.sh
